import type { CampaignType } from './types'

export const campaignsMock: CampaignType[] = [
  {
    status: 'LIVE TABLE',
    gameUuid: 'daf3e8c0-1b2a-4d3e-9f5a-1c2b3d4e5f60',
    statusTone: 'success',
    title: 'Ashfall Cartography',
    details: '12 scenes · 4 active notes',
    description: 'Last session 2h ago',
    footerLeft: 'Session 18 queued',
    footerRight: 'Autosaved',
    footerTone: 'text-emerald-400',
    last_change: '2024-06-01T12:34:56Z',
  },
  {
    status: 'PREP MODE',
    gameUuid: 'a5df3e8c-1b2a-4d3e-9f5a-1c2b3d4e5f61',
    statusTone: 'default',
    title: 'Signal Under Glass',
    details: '7 scenes · 22 references',
    description: 'Timeline locked for next session',
    footerLeft: '3 blockers',
    footerRight: 'Need scene beats',
    footerTone: 'text-amber-400',
    last_change: '2026-06-02T09:15:30Z',
  },
  {
    status: 'ON HOLD',
    statusTone: 'secondary',
    gameUuid: '9e4f3e8c-1b2a-4d3e-9f5a-1c2b3d4e5f62',
    title: 'The Seventh Relay',
    details: '5 scenes · 1 encounter',
    description: 'draft · Imported from archive branch',
    footerLeft: 'Paused after session 3',
    footerRight: 'Resume when ready',
    footerTone: 'text-slate-500',
    last_change: '2026-05-03T14:20:00Z',
  },
  {
    status: 'ON HOLD',
    statusTone: 'secondary',
    gameUuid: '9e4f3e8c-1b2a-4d3e-9f5a-1c2b3d4e5f62',
    title: 'The Seventh Relay',
    details: '5 scenes · 1 encounter',
    description: 'draft · Imported from archive branch',
    footerLeft: 'Paused after session 3',
    footerRight: 'Resume when ready',
    footerTone: 'text-slate-500',
    last_change: '2026-05-03T14:20:00Z',
  },
  {
    status: 'ON HOLD',
    statusTone: 'secondary',
    gameUuid: '9e4f3e8c-1b2a-4d3e-9f5a-1c2b3d4e5f62',
    title: 'The Seventh Relay',
    details: '5 scenes · 1 encounter',
    description: 'draft · Imported from archive branch',
    footerLeft: 'Paused after session 3',
    footerRight: 'Resume when ready',
    footerTone: 'text-slate-500',
    last_change: '2026-05-04T14:20:00Z'
  },
  {
    status: 'ON HOLD',
    statusTone: 'secondary',
    gameUuid: '9e4f3e8c-1b2a-4d3e-9f5a-1c2b3d4e5f62',
    title: 'The Seventh Relay',
    details: '5 scenes · 1 encounter',
    description: 'draft · Imported from archive branch',
    footerLeft: 'Paused after session 3',
    footerRight: 'Resume when ready',
    footerTone: 'text-slate-500',
    last_change: '2026-05-23T14:20:00Z'
  },
  {
    status: 'ON HOLD',
    statusTone: 'secondary',
    gameUuid: '9e4f3e8c-1b2a-4d3e-9f5a-1c2b3d4e5f62',
    title: 'The Seventh Relay',
    details: '5 scenes · 1 encounter',
    description: 'draft · Imported from archive branch',
    footerLeft: 'Paused after session 3',
    footerRight: 'Resume when ready',
    footerTone: 'text-slate-500',
    last_change: '2026-05-23T14:20:00Z'
  },
] 
